# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/eshop-parent" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Ho_Chi_Minh"
    target-branch: "develop"
    commit-message:
      prefix: "Dependabot update"
    pull-request-branch-name:
      separator: "-"
    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates at 0:00 every Monday - UTC
    schedule:
      interval: "weekly"
      time: "00:00"
    target-branch: "develop"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/sag-rest" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Ho_Chi_Minh"
    target-branch: "develop"
    commit-message:
      prefix: "Dependabot update"
    pull-request-branch-name:
      separator: "-"
    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/sag-common" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Ho_Chi_Minh"
    target-branch: "develop"
    commit-message:
      prefix: "Dependabot update"
    pull-request-branch-name:
      separator: "-"
    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates at 0:00 every Monday - UTC
    schedule:
      interval: "weekly"
      time: "00:00"
    target-branch: "develop"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/sag-oauth2" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Ho_Chi_Minh"
    target-branch: "develop"
    commit-message:
      prefix: "Dependabot update"
    pull-request-branch-name:
      separator: "-"
    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates at 0:00 every Monday - UTC
    schedule:
      interval: "weekly"
      time: "00:00"
    target-branch: "develop"
    
  - package-ecosystem: "npm"
    directory: "/eshop-web"
    # Check for updates at 0:00 every Monday - UTC
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    target-branch: "develop"
    ignore:
      - dependency-name: "mongoose"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "azure-functions-core-tools"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]
      - dependency-name: "@typescript-eslint/parser"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "npm"
    directory: "/eshop-backoffice"
    # Check for updates at 0:00 every Monday - UTC
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    target-branch: "develop"
    ignore:
      - dependency-name: "mongoose"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "azure-functions-core-tools"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]
      - dependency-name: "@typescript-eslint/parser"
        update-types: ["version-update:semver-patch"]
    
      
      
